"""
ReportLab PDF generation for settlement sheets.
Takes a settlement dict (from get_settlement) and returns PDF bytes.
"""
from io import BytesIO
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib import colors

def generate_settlement_pdf(settlement):
    """
    Generate a PDF settlement sheet.

    Args:
        settlement: sqlite3.Row from get_settlement() -- has all joined fields

    Returns: bytes (PDF content)

    Usage:
        settlement = get_settlement(conn, settlement_id)
        pdf_bytes = generate_settlement_pdf(settlement)
        return Response(pdf_bytes, mimetype='application/pdf',
                        headers={'Content-Disposition': f'attachment; filename=settlement_{settlement_id}.pdf'})
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter,
                            topMargin=0.75*inch, bottomMargin=0.75*inch)
    styles = getSampleStyleSheet()
    elements = []

    # Header
    elements.append(Paragraph(f"Settlement Sheet", styles['Title']))
    elements.append(Paragraph(f"Event: {settlement['event_name']}", styles['Heading2']))
    elements.append(Paragraph(
        f"Date: {settlement['event_date']} | Venue: {settlement['venue_name']} | Room: {settlement['room_name']}",
        styles['Normal']
    ))
    elements.append(Spacer(1, 0.25*inch))

    # Parties
    elements.append(Paragraph(f"Musician: {settlement['musician_name']}", styles['Normal']))
    elements.append(Paragraph(f"Deal Type: {settlement['deal_type'].replace('_', ' ').title()}", styles['Normal']))
    elements.append(Spacer(1, 0.25*inch))

    # Financial breakdown
    def fmt_dollars(cents):
        return f"${cents / 100:,.2f}"

    data = [
        ['Item', 'Amount'],
        ['Door Revenue', fmt_dollars(settlement['door_revenue_cents'])],
        ['Expenses', f"({fmt_dollars(settlement['expenses_cents'])})"],
        ['Musician Payout', fmt_dollars(settlement['musician_payout_cents'])],
        ['Venue Share', fmt_dollars(settlement['venue_share_cents'])],
        ['Promoter Fee', fmt_dollars(settlement['promoter_fee_cents'])],
        ['Tax', fmt_dollars(settlement['tax_amount_cents'])],
    ]

    table = Table(data, colWidths=[4*inch, 2*inch])
    table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (1, 0), (1, -1), 'RIGHT'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.black),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.lightgrey]),
    ]))
    elements.append(table)
    elements.append(Spacer(1, 0.5*inch))

    # Signature lines
    elements.append(Paragraph("Signatures:", styles['Heading3']))
    elements.append(Spacer(1, 0.3*inch))
    elements.append(Paragraph("Venue Manager: _________________________  Date: __________", styles['Normal']))
    elements.append(Spacer(1, 0.2*inch))
    elements.append(Paragraph("Musician: _________________________  Date: __________", styles['Normal']))
    elements.append(Spacer(1, 0.5*inch))

    # Footer
    elements.append(Paragraph(
        f"Generated by VenueConnect on {settlement['created_at']}",
        styles['Normal']
    ))

    doc.build(elements)
    return buffer.getvalue()
