/**
 * Provenance Chain PDF Export.
 *
 * Uses @react-pdf/renderer to generate a PDF with:
 *   1. Header with project title + generation date + disclaimer
 *   2. Summary stats table
 *   3. Entry-by-entry provenance log table
 *      (Department | Task | Attribution | Tool | Human | Notes)
 *   4. Footer with "Generated by Ethics Toolkit. Guidance, not legal advice."
 *
 * Filename convention: provenance-chain-{projectTitle}-{date}.pdf
 *
 * Spec reference: Section 4 Tool 4 -- PDF Export Format (Premium)
 */

import React from 'react';
import {
  Document,
  Page,
  Text,
  View,
  StyleSheet,
} from '@react-pdf/renderer';
import type { ProvenanceOutputType } from '@/lib/schemas/provenance';

const styles = StyleSheet.create({
  page: {
    padding: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
  },
  header: {
    marginBottom: 20,
  },
  title: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  subtitle: {
    fontSize: 10,
    color: '#666666',
    marginBottom: 4,
  },
  disclaimer: {
    fontSize: 8,
    color: '#999999',
    fontStyle: 'italic',
  },
  sectionTitle: {
    fontSize: 13,
    fontWeight: 'bold',
    marginTop: 16,
    marginBottom: 8,
  },
  // Summary stats table
  summaryTable: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#cccccc',
    marginBottom: 16,
  },
  summaryCell: {
    flex: 1,
    padding: 8,
    borderRightWidth: 1,
    borderRightColor: '#cccccc',
    alignItems: 'center',
  },
  summaryCellLast: {
    flex: 1,
    padding: 8,
    alignItems: 'center',
  },
  summaryValue: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  summaryLabel: {
    fontSize: 8,
    color: '#666666',
    marginTop: 2,
  },
  // Entry log table
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#f3f4f6',
    borderWidth: 1,
    borderColor: '#cccccc',
    borderBottomWidth: 0,
  },
  tableRow: {
    flexDirection: 'row',
    borderWidth: 1,
    borderColor: '#cccccc',
    borderTopWidth: 0,
  },
  colDept: {
    width: '14%',
    padding: 4,
    borderRightWidth: 1,
    borderRightColor: '#cccccc',
  },
  colTask: {
    width: '22%',
    padding: 4,
    borderRightWidth: 1,
    borderRightColor: '#cccccc',
  },
  colAttr: {
    width: '14%',
    padding: 4,
    borderRightWidth: 1,
    borderRightColor: '#cccccc',
  },
  colTool: {
    width: '16%',
    padding: 4,
    borderRightWidth: 1,
    borderRightColor: '#cccccc',
  },
  colHuman: {
    width: '16%',
    padding: 4,
    borderRightWidth: 1,
    borderRightColor: '#cccccc',
  },
  colNotes: {
    width: '18%',
    padding: 4,
  },
  headerText: {
    fontWeight: 'bold',
    fontSize: 8,
  },
  cellText: {
    fontSize: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 40,
    right: 40,
    textAlign: 'center',
    fontSize: 8,
    color: '#999999',
  },
});

function formatAttribution(attr: string): string {
  return attr.replace(/_/g, ' ').replace(/\b\w/g, (c) => c.toUpperCase());
}

interface ProvenancePDFProps {
  data: ProvenanceOutputType;
}

export function ProvenancePDF({ data }: ProvenancePDFProps) {
  const generatedDate = new Date(data.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });

  return React.createElement(
    Document,
    null,
    React.createElement(
      Page,
      { size: 'A4', style: styles.page },
      // 1. Header
      React.createElement(
        View,
        { style: styles.header },
        React.createElement(Text, { style: styles.title }, `Provenance Chain: ${data.projectTitle}`),
        React.createElement(Text, { style: styles.subtitle }, `Generated: ${generatedDate}`),
        React.createElement(
          Text,
          { style: styles.disclaimer },
          'Guidance, not legal advice. Consult an entertainment attorney for legal counsel.'
        )
      ),
      // 2. Summary Stats Table
      React.createElement(Text, { style: styles.sectionTitle }, 'Summary'),
      React.createElement(
        View,
        { style: styles.summaryTable },
        React.createElement(
          View,
          { style: styles.summaryCell },
          React.createElement(Text, { style: styles.summaryValue }, String(data.summary.totalEntries)),
          React.createElement(Text, { style: styles.summaryLabel }, 'Total Entries')
        ),
        React.createElement(
          View,
          { style: styles.summaryCell },
          React.createElement(Text, { style: styles.summaryValue }, String(data.summary.humanMade)),
          React.createElement(Text, { style: styles.summaryLabel }, 'Human Made')
        ),
        React.createElement(
          View,
          { style: styles.summaryCell },
          React.createElement(Text, { style: styles.summaryValue }, String(data.summary.aiAssisted)),
          React.createElement(Text, { style: styles.summaryLabel }, 'AI Assisted')
        ),
        React.createElement(
          View,
          { style: styles.summaryCell },
          React.createElement(Text, { style: styles.summaryValue }, String(data.summary.aiGenerated)),
          React.createElement(Text, { style: styles.summaryLabel }, 'AI Generated')
        ),
        React.createElement(
          View,
          { style: styles.summaryCellLast },
          React.createElement(Text, { style: styles.summaryValue }, `${data.summary.percentageHuman}%`),
          React.createElement(Text, { style: styles.summaryLabel }, 'Human')
        )
      ),
      // 3. Entry-by-entry provenance log table
      React.createElement(Text, { style: styles.sectionTitle }, 'Provenance Log'),
      // Table header
      React.createElement(
        View,
        { style: styles.tableHeader },
        React.createElement(View, { style: styles.colDept }, React.createElement(Text, { style: styles.headerText }, 'Department')),
        React.createElement(View, { style: styles.colTask }, React.createElement(Text, { style: styles.headerText }, 'Task')),
        React.createElement(View, { style: styles.colAttr }, React.createElement(Text, { style: styles.headerText }, 'Attribution')),
        React.createElement(View, { style: styles.colTool }, React.createElement(Text, { style: styles.headerText }, 'Tool')),
        React.createElement(View, { style: styles.colHuman }, React.createElement(Text, { style: styles.headerText }, 'Human')),
        React.createElement(View, { style: styles.colNotes }, React.createElement(Text, { style: styles.headerText }, 'Notes'))
      ),
      // Table rows
      ...data.entries.map((entry, i) =>
        React.createElement(
          View,
          { style: styles.tableRow, key: i },
          React.createElement(View, { style: styles.colDept }, React.createElement(Text, { style: styles.cellText }, entry.department)),
          React.createElement(View, { style: styles.colTask }, React.createElement(Text, { style: styles.cellText }, entry.taskDescription)),
          React.createElement(View, { style: styles.colAttr }, React.createElement(Text, { style: styles.cellText }, formatAttribution(entry.attribution))),
          React.createElement(View, { style: styles.colTool }, React.createElement(Text, { style: styles.cellText }, entry.toolUsed || '-')),
          React.createElement(View, { style: styles.colHuman }, React.createElement(Text, { style: styles.cellText }, entry.humanContributor || '-')),
          React.createElement(View, { style: styles.colNotes }, React.createElement(Text, { style: styles.cellText }, entry.notes || '-'))
        )
      ),
      // 4. Footer
      React.createElement(
        Text,
        { style: styles.footer },
        'Generated by Ethics Toolkit. Guidance, not legal advice.'
      )
    )
  );
}

/**
 * Generate the filename for a provenance PDF export.
 */
export function getProvenancePDFFilename(projectTitle: string): string {
  const sanitized = projectTitle
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
  const date = new Date().toISOString().split('T')[0];
  return `provenance-chain-${sanitized}-${date}.pdf`;
}
